;;; flycheck-clang-analyzer-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-clang-analyzer.el

(autoload 'flycheck-clang-analyzer-setup "flycheck-clang-analyzer" "\
Setup flycheck-clang-analyzer.

Add `clang-analyzer' to `flycheck-checkers'." t)
(register-definition-prefixes "flycheck-clang-analyzer" '("flycheck-clang-analyzer--"))

;;; End of scraped data

(provide 'flycheck-clang-analyzer-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-clang-analyzer-autoloads.el ends here
