;;; x86-lookup-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from x86-lookup.el

(autoload 'x86-lookup "x86-lookup" "\
Jump to the PDF documentation for MNEMONIC.
Defaults to the mnemonic under point.

(fn MNEMONIC)" t)
(register-definition-prefixes "x86-lookup" '("x86-lookup-"))

;;; End of scraped data

(provide 'x86-lookup-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; x86-lookup-autoloads.el ends here
